"""ホットコメントのモックデータ（アンチ系・長文相談系）"""
from datetime import date, timedelta
import random

TODAY = date.today()


def get_mock_hot_comments() -> dict:
    return {
        "anti": [
            {
                "id": "anti_001",
                "post_title": "学級開きで「絶対やってはいけないこと」3選",
                "post_url": "https://www.instagram.com/p/sample001/",
                "comment": "こんなの当たり前のことで、わざわざ投稿する必要ありますか？現場をなめてると思います。こういう薄い内容が拡散されるのが本当に嫌です。",
                "username": "anonymous_teacher",
                "timestamp": (TODAY - timedelta(days=1)).isoformat(),
                "likes": 3,
                "emotion": "批判・怒り",
                "handling_note": "スルーでOK。ただし「当たり前だからこそ確認する価値がある」という視点で、次の投稿のフックとして使える。同様の声が続くなら丁寧に返答。",
                "content_potential": "スタエフで『当たり前だと思われてる教育論』というテーマで語れる",
            },
            {
                "id": "anti_002",
                "post_title": "保護者からのクレーム、最初の30秒で決まる対応術",
                "post_url": "https://www.instagram.com/p/sample002/",
                "comment": "先生側の視点しかなくてバイアスがすごい。保護者にも事情があるんです。こういう投稿が教員と保護者の溝を深めてると思います。",
                "username": "parent_voice_2024",
                "timestamp": (TODAY - timedelta(days=2)).isoformat(),
                "likes": 18,
                "emotion": "批判・反論",
                "handling_note": "いいねが18件ついており無視できない。「保護者視点も当然大切で、両者の対話こそが鍵」という投稿で回収するとファンが増える可能性がある。",
                "content_potential": "『保護者の本音と先生の本音、両方語る』企画投稿でポジティブに回収できる",
            },
            {
                "id": "anti_003",
                "post_title": "先生が病む前に知っておきたいこと",
                "post_url": "https://www.instagram.com/p/sample003/",
                "comment": "きれいごとばかりでうんざりします。こういう投稿で救われる先生がいるのかもしれないけど、現場の深刻さをわかってないと感じます。もっと本質を語ってほしい。",
                "username": "burnout_teacher",
                "timestamp": (TODAY - timedelta(days=3)).isoformat(),
                "likes": 42,
                "emotion": "失望・不満",
                "handling_note": "いいねが42件と多く、共感している人が多い。「きれいごとに聞こえてしまったとしたら申し訳ない」という謙虚な返答＋より深い本音トークへの誘導が有効。",
                "content_potential": "『きれいごとではなく本音で語る教員の現実』というスタエフエピソードのネタに昇華できる",
            },
            {
                "id": "anti_004",
                "post_title": "新年度の職員室、先生の本音をぶっちゃける",
                "post_url": "https://www.instagram.com/p/sample004/",
                "comment": "SNSで稼ぎながら「現場の先生の声を届ける」とか言ってる人を信用できません。本当に大変なら学校を離れずSNS発信なんてしていられないはずでは？",
                "username": "skeptical_edu",
                "timestamp": TODAY.isoformat(),
                "likes": 7,
                "emotion": "懐疑・不信",
                "handling_note": "「なぜSNS発信をしているのか」という問いかけに誠実に答えることで信頼が生まれる。動機を正直に語るストーリーを作るチャンス。",
                "content_potential": "『なぜ現役教員がSNSで発信するのか、本音を話す』という自己開示投稿のネタになる",
            },
        ],
        "long_consultation": [
            {
                "id": "consult_001",
                "post_title": "学級開きで「絶対やってはいけないこと」3選",
                "post_url": "https://www.instagram.com/p/sample001/",
                "comment": "ダイ先生、初めてコメントします。今年度から初めて担任を持つことになりました。配属は3年生（9歳）のクラスで28人います。学級開きで何から準備すればいいか全くわからず、この投稿を見てすごく参考になりました。ただ、私のクラスには前担任とのトラブルで保護者からの不信感が残っているという引き継ぎがあり、最初の懇談会をどう乗り越えるかが今一番の不安です。何かアドバイスをいただけると嬉しいです。長文すみません。",
                "username": "new_teacher_2026",
                "timestamp": (TODAY - timedelta(days=1)).isoformat(),
                "likes": 89,
                "topic": "新任担任×前担任トラブルの引き継ぎ対応",
                "emotion": "不安・期待",
                "content_potential": "高",
                "suggested_use": "スタエフの「お悩み相談回」のメイン相談として使える。同じ悩みを抱える新任が多く、共感爆発が期待できる。",
                "recommended_format": ["スタエフ", "Instagram"],
            },
            {
                "id": "consult_002",
                "post_title": "保護者対応で失敗しないための思考法",
                "post_url": "https://www.instagram.com/p/sample002/",
                "comment": "ダイ先生こんにちは。小学校4年担任5年目の者です。今年度、特定の保護者（Aさん）から週に3〜4回、長い時には1時間近い電話がかかってきます。内容は「うちの子がクラスでいじめられている」というものですが、子ども同士の確認ではそのような事実は確認できておらず、管理職にも相談済みです。ただ管理職からは「保護者の気持ちに寄り添って」と言われるだけで具体的な対応策を教えてもらえず、精神的に限界を感じています。このような場合、どのように対応すればよいでしょうか。本当に苦しいです。",
                "username": "teacher_5years",
                "timestamp": (TODAY - timedelta(days=2)).isoformat(),
                "likes": 203,
                "topic": "クレーム保護者の執拗な電話対応と管理職不対応",
                "emotion": "疲弊・助けを求める",
                "content_potential": "非常に高",
                "suggested_use": "YouTubeライブのメインテーマとして使える。「管理職が助けてくれない時に教師ができること」というタイトルでかなりの視聴が見込める。",
                "recommended_format": ["YouTubeライブ", "スタエフ"],
            },
            {
                "id": "consult_003",
                "post_title": "不登校の子への最初の一歩",
                "post_url": "https://www.instagram.com/p/sample003/",
                "comment": "先生、5年生の担任をしています。クラスに4月から一度も登校できていない子がいます。家庭への電話には出てもらえるのですが、家庭訪問は断られています。スクールカウンセラーにもつなぎましたが、本人が面談を拒否しています。このまま連絡を取り続けるだけでいいのか、何か自分にできることがあるのではないかと毎日考えています。担任として何ができるか教えてもらえませんか。",
                "username": "class_teacher_5th",
                "timestamp": (TODAY - timedelta(days=4)).isoformat(),
                "likes": 156,
                "topic": "新年度から不登校・家庭が閉鎖的なケース",
                "emotion": "焦り・無力感・責任感",
                "content_potential": "高",
                "suggested_use": "「不登校対応の初動3ステップ」フィード投稿＋詳細はスタエフという2段構えのコンテンツに最適。",
                "recommended_format": ["Instagram", "スタエフ"],
            },
            {
                "id": "consult_004",
                "post_title": "部活指導ゼロでも評価された理由",
                "post_url": "https://www.instagram.com/p/sample004/",
                "comment": "先生の投稿をいつも拝見しています。私は30代の教員ですが、副校長から「部活動に積極的でないと評価に影響する」と言われました。私自身は担当していない競技の部活顧問を押し付けられており、土日の活動でプライベートが全くありません。先生のように断れる環境がうらやましいです。自分の学校でも断りたいのですが、波風を立てずに断る具体的な言い方を教えてもらえませんか。現実的に難しいのはわかっているんですが…。",
                "username": "tired_teacher_30s",
                "timestamp": (TODAY - timedelta(days=5)).isoformat(),
                "likes": 178,
                "topic": "部活断れない・評価脅しへの対処",
                "emotion": "疲弊・諦め・助けを求める",
                "content_potential": "高",
                "suggested_use": "「部活を断るための具体的な言い方テンプレ」投稿は保存率が爆上がりするはず。YouTubeライブでロールプレイ形式で語るのも有効。",
                "recommended_format": ["Instagram", "YouTubeライブ"],
            },
        ],
    }
