"""教育系ニュース・Xトレンドのモックデータ"""
from datetime import date, timedelta
import random

TODAY = date.today()


def get_mock_news() -> list[dict]:
    return [
        {
            "id": "news_001",
            "title": "全国1000校超で「代替教員なし」産育休でクラス担任が空白に",
            "url": "https://www.kyoiku-shimbun.co.jp/article/sample001",
            "source_type": "教育新聞",
            "source_name": "教育新聞",
            "published_at": (TODAY - timedelta(days=1)).isoformat(),
            "genre_tags": ["教員不足", "働き方", "産育休", "学校制度"],
            "trend_score": 91,
            "emotions": [
                {"type": "怒り", "intensity": 0.55},
                {"type": "不安", "intensity": 0.35},
                {"type": "共感", "intensity": 0.10},
            ],
            "connection_score": 5,
            "formats": ["スタエフ", "YouTubeライブ", "フィード"],
            "angle_memo": "「先生がいないクラスで子どもたちはどうなるのか」という当事者視点で語れる。怒りではなく「リアルな現場の声」として届けると拡散しやすい。",
            "caution_level": "中",
            "caution_reason": "行政批判に寄りすぎると炎上リスク。「現場の工夫」にフォーカスすると安全。",
            "x_rt_count": 3840,
            "x_like_count": 12600,
            "summary": "産休・育休取得による代替教員の確保が全国で困難になっており、担任不在のまま新年度を迎えた学校が1000校を超えた。",
        },
        {
            "id": "news_002",
            "title": "新年度の職員室「名前を覚える前に業務が始まる」新任教員の孤立が深刻",
            "url": "https://x.com/sensei_voice/status/1909876543210",
            "source_type": "X",
            "source_name": "@sensei_voice（教員ツイート）",
            "published_at": TODAY.isoformat(),
            "genre_tags": ["新年度", "新任教員", "職員室", "メンタルヘルス"],
            "trend_score": 88,
            "emotions": [
                {"type": "共感", "intensity": 0.60},
                {"type": "不安", "intensity": 0.25},
                {"type": "驚き", "intensity": 0.15},
            ],
            "connection_score": 5,
            "formats": ["リール", "スタエフ", "フィード"],
            "angle_memo": "4月の新年度タイミングと完全合致。「自分もそうだった」という体験談リールが最強。コメント欄が自然と盛り上がる構造。",
            "caution_level": "低",
            "caution_reason": "共感系なので炎上リスクは低い。ただし「学校が悪い」断定は避ける。",
            "x_rt_count": 5210,
            "x_like_count": 24300,
            "summary": "新年度初日から膨大な業務に直面する新任教員の孤立感を訴えた投稿が拡散。同じ経験を持つ教員たちの共感コメントが殺到している。",
        },
        {
            "id": "news_003",
            "title": "部活動の地域移行、実態は「教師が無償ボランティア」として継続",
            "url": "https://www.kanaloco.jp/news/social/article-sample003",
            "source_type": "地方新聞",
            "source_name": "神奈川新聞",
            "published_at": (TODAY - timedelta(days=2)).isoformat(),
            "genre_tags": ["部活問題", "働き方", "地域移行", "無償労働"],
            "trend_score": 79,
            "emotions": [
                {"type": "怒り", "intensity": 0.65},
                {"type": "疲労感", "intensity": 0.25},
                {"type": "あきらめ", "intensity": 0.10},
            ],
            "connection_score": 4,
            "formats": ["YouTubeライブ", "スタエフ", "フィード"],
            "angle_memo": "「制度と現実のギャップ」を主テーマにするとインテリ層にも刺さる。「私の学校では…」という体験談をセットにするのが効果的。",
            "caution_level": "中",
            "caution_reason": "管理職・行政への批判になりやすい。「現場目線での提言」スタイルを維持する。",
            "x_rt_count": 2190,
            "x_like_count": 8750,
            "summary": "部活動の地域移行が進む中、実際には教師がボランティアとして従前と変わらず指導を継続している実態が報告されている。",
        },
        {
            "id": "news_004",
            "title": "「モンペ」という言葉に違和感　保護者対応で疲弊する教師と孤立する親",
            "url": "https://x.com/education_jp/status/1910123456789",
            "source_type": "X",
            "source_name": "@education_jp（教育系アカウント）",
            "published_at": (TODAY - timedelta(days=1)).isoformat(),
            "genre_tags": ["保護者対応", "コミュニケーション", "学校と家庭"],
            "trend_score": 83,
            "emotions": [
                {"type": "共感", "intensity": 0.45},
                {"type": "悲しみ", "intensity": 0.30},
                {"type": "驚き", "intensity": 0.25},
            ],
            "connection_score": 5,
            "formats": ["フィード", "リール", "スタエフ"],
            "angle_memo": "「先生視点」と「保護者視点」の両側を描くと、どちらにも刺さる。「正解より対話を」というダイ先生の発信スタイルと相性最高。",
            "caution_level": "低",
            "caution_reason": "両者の立場を尊重すれば炎上しにくい。どちらかを悪者にしない言い方が重要。",
            "x_rt_count": 4480,
            "x_like_count": 19200,
            "summary": "「モンスターペアレント」という言葉が教師と保護者の断絶を深めているという投稿がX上で大きな反響。双方の疲弊を可視化する声が集まった。",
        },
        {
            "id": "news_005",
            "title": "教員の不祥事報道「現場の空気が重い」SNSで声が続々",
            "url": "https://x.com/search?q=%E6%95%99%E5%93%A1+%E4%B8%8D%E7%A5%A5%E4%BA%8B&f=live",
            "source_type": "X",
            "source_name": "複数教員アカウント",
            "published_at": TODAY.isoformat(),
            "genre_tags": ["不祥事", "教員イメージ", "メンタルヘルス", "現場の声"],
            "trend_score": 72,
            "emotions": [
                {"type": "落胆", "intensity": 0.40},
                {"type": "怒り", "intensity": 0.30},
                {"type": "不安", "intensity": 0.30},
            ],
            "connection_score": 3,
            "formats": ["スタエフ", "フィード"],
            "angle_memo": "「不祥事を起こした一部の人と、誠実に働く多数の先生」という構図を打ち出す。真面目に働く先生へのエールとして届けるとポジティブな反応になりやすい。",
            "caution_level": "高",
            "caution_reason": "不祥事を直接話題にすると批判の矛先になりやすい。「教師全体のイメージ」という切り口に昇華させること。",
            "x_rt_count": 1620,
            "x_like_count": 5430,
            "summary": "教員による不祥事報道が続く中、「自分も白い目で見られる」「仕事のモチベーションが下がる」と現場教員がSNSで心境を吐露。",
        },
        {
            "id": "news_006",
            "title": "「給特法」見直し議論が加速、残業代支給への期待と不安入り混じる",
            "url": "https://www.kyoiku-shimbun.co.jp/article/sample006",
            "source_type": "教育新聞",
            "source_name": "教育新聞",
            "published_at": (TODAY - timedelta(days=3)).isoformat(),
            "genre_tags": ["給特法", "残業代", "働き方改革", "学校制度"],
            "trend_score": 76,
            "emotions": [
                {"type": "期待", "intensity": 0.40},
                {"type": "不安", "intensity": 0.35},
                {"type": "懐疑", "intensity": 0.25},
            ],
            "connection_score": 3,
            "formats": ["YouTubeライブ", "スタエフ"],
            "angle_memo": "「給特法って何？」という解説動画はそれだけで需要がある。複雑な制度をわかりやすく解説するダイ先生の得意分野と合致。",
            "caution_level": "中",
            "caution_reason": "政策議論は両論あるため断定的な意見は避ける。「現場から見た解説」スタンスで。",
            "x_rt_count": 980,
            "x_like_count": 3200,
            "summary": "教員の時間外労働に関わる「給特法」の見直し議論が活発化。残業代支給への期待がある一方、業務量が増えるだけとの懸念も。",
        },
        {
            "id": "news_007",
            "title": "「先生、疲れてますか？」生徒からの手紙がXで10万いいね",
            "url": "https://x.com/teacher_diary/status/1911234567890",
            "source_type": "X",
            "source_name": "@teacher_diary（教師日記アカウント）",
            "published_at": (TODAY - timedelta(days=1)).isoformat(),
            "genre_tags": ["師弟関係", "感動", "教師のやりがい", "メンタルヘルス"],
            "trend_score": 95,
            "emotions": [
                {"type": "感動", "intensity": 0.70},
                {"type": "共感", "intensity": 0.20},
                {"type": "温かさ", "intensity": 0.10},
            ],
            "connection_score": 4,
            "formats": ["リール", "フィード", "スタエフ"],
            "angle_memo": "教師のやりがいを語る切り口として最適。「しんどくてもやめられない理由」という本音トークのフックとして使える。感情量が多いのでリールでバズりやすい。",
            "caution_level": "低",
            "caution_reason": "ポジティブな話題なのでリスクはほぼなし。ただし実際の手紙内容の引用は権利的にNG。",
            "x_rt_count": 8900,
            "x_like_count": 102000,
            "summary": "「先生、疲れてますか？ありがとう」と生徒が書いた手紙をシェアした投稿が10万いいねを超えた。教師の孤独と感謝に関するコメントが殺到している。",
        },
        {
            "id": "news_008",
            "title": "4月の学級開きで「つまずく」若手教員、理由はマニュアルが存在しないから",
            "url": "https://www.hokkaido-np.co.jp/article/sample008",
            "source_type": "地方新聞",
            "source_name": "北海道新聞",
            "published_at": (TODAY - timedelta(days=2)).isoformat(),
            "genre_tags": ["新年度", "学級経営", "若手教員", "OJT"],
            "trend_score": 81,
            "emotions": [
                {"type": "不安", "intensity": 0.50},
                {"type": "共感", "intensity": 0.35},
                {"type": "驚き", "intensity": 0.15},
            ],
            "connection_score": 5,
            "formats": ["フィード", "リール", "YouTubeライブ"],
            "angle_memo": "「学級開きでやること・やってはいけないこと」という実践的なコンテンツに直結。ダイ先生の経験談＋具体的Tips形式にすると保存率が爆上がりする。",
            "caution_level": "低",
            "caution_reason": "解説・ノウハウ系なのでほぼリスクなし。特定の学校・人物への言及は避ける。",
            "x_rt_count": 3120,
            "x_like_count": 11400,
            "summary": "4月の学級開きは教師にとって最も重要な場面の一つだが、体系的なマニュアルが存在せず、若手教員が試行錯誤している実態が報告された。",
        },
    ]


def get_mock_x_trends() -> list[dict]:
    """Xのトレンドキーワードのモック"""
    return [
        {"keyword": "#教員不足", "tweet_count": 42000, "trend": "up"},
        {"keyword": "#新年度", "tweet_count": 210000, "trend": "up"},
        {"keyword": "#部活動地域移行", "tweet_count": 18000, "trend": "stable"},
        {"keyword": "#給特法", "tweet_count": 8700, "trend": "up"},
        {"keyword": "#先生大変", "tweet_count": 31000, "trend": "up"},
        {"keyword": "#保護者対応", "tweet_count": 14000, "trend": "stable"},
        {"keyword": "#学級開き", "tweet_count": 55000, "trend": "up"},
        {"keyword": "#教師のリアル", "tweet_count": 28000, "trend": "up"},
    ]
