"""昨年同時期（4月前後）の高エンゲージメント投稿モックデータ"""
from datetime import date


def get_mock_past_posts() -> list[dict]:
    return [
        {
            "id": "past_001",
            "title": "4月の学級開き、やって良かったこと・悪かったこと【本音】",
            "period": "2025年4月7日",
            "media_type": "IMAGE",
            "url": "https://www.instagram.com/p/past_sample001/",
            "like_count": 1243,
            "comments_count": 94,
            "engagement": 1525,
            "caption_snippet": "【4月の学級開き、正直に言います】\n\n去年やって良かったこと、正直失敗だったこと。\n両方ぶっちゃけます。\n\n#学級経営 #新年度 #学級開き #先生あるある",
            "hashtags": ["#学級経営", "#新年度", "#学級開き", "#先生あるある"],
            "what_worked": "失敗談を入れたことで「私もそうだった」系の共感コメントが殺到。保存数が過去最多だった。",
            "seasonal_match": True,
            "repurpose_idea": "今年も同じ切り口でリール化するとバズ確実。「2025年版→2026年版」のアップデートも効果的。",
            "trend_overlap": ["学級開き", "新年度", "教員不足"],
        },
        {
            "id": "past_002",
            "title": "新任1年目の4月、あの頃の私に伝えたいこと",
            "period": "2025年4月12日",
            "media_type": "VIDEO",
            "url": "https://www.instagram.com/p/past_sample002/",
            "like_count": 987,
            "comments_count": 112,
            "engagement": 1323,
            "caption_snippet": "【新任1年目の4月に戻れるなら、これだけ伝えたい】\n\n当時の私は本当に何もわからなかった。\n\n#新任教員 #先生1年目 #教員採用 #教育",
            "hashtags": ["#新任教員", "#先生1年目", "#教員採用"],
            "what_worked": "「新任の頃の自分へ」という手紙形式が刺さった。新任・採用試験受験生からの保存とDMが急増した。",
            "seasonal_match": True,
            "repurpose_idea": "今年の新任に向けたバージョンで出すと同様の反響が見込める。4月上旬に出すのが最適タイミング。",
            "trend_overlap": ["新任教員", "新年度", "教員不足"],
        },
        {
            "id": "past_003",
            "title": "担任を持って3週間、正直しんどい話",
            "period": "2025年4月21日",
            "media_type": "IMAGE",
            "url": "https://www.instagram.com/p/past_sample003/",
            "like_count": 1876,
            "comments_count": 203,
            "engagement": 2485,
            "caption_snippet": "【担任3週間、正直ぶっちゃけます】\n\n毎年この時期にしんどくなる先生が多い。\n気合いだけじゃ乗り越えられないことがある。\n\n#先生の本音 #教員の働き方 #新年度",
            "hashtags": ["#先生の本音", "#教員の働き方", "#新年度"],
            "what_worked": "「3週間目」というタイミングの絶妙さ。4月後半の中だるみ・疲弊感に刺さった。コメント欄が自然と「私もしんどい」の共有スペースになった。",
            "seasonal_match": True,
            "repurpose_idea": "4月下旬（21〜28日あたり）に同じ切り口で出すと再現性が高い。今年のリアルな状況を加えて更新版を出す。",
            "trend_overlap": ["教員の働き方", "メンタルヘルス", "新年度"],
        },
        {
            "id": "past_004",
            "title": "保護者の最初の印象を決める「最初の学級通信」の書き方",
            "period": "2025年4月9日",
            "media_type": "CAROUSEL_ALBUM",
            "url": "https://www.instagram.com/p/past_sample004/",
            "like_count": 743,
            "comments_count": 58,
            "engagement": 917,
            "caption_snippet": "【最初の学級通信で保護者の心を掴む方法】\n\n最初の1枚で、その先生への信頼度が決まります。\n実際に使えるテンプレ付き📝\n\n#学級通信 #保護者対応 #学級経営",
            "hashtags": ["#学級通信", "#保護者対応", "#学級経営"],
            "what_worked": "「テンプレ付き」が保存率を大幅に押し上げた。実用系コンテンツの強さを証明した投稿。",
            "seasonal_match": True,
            "repurpose_idea": "今年版のテンプレをアップデートして再投稿。「2026年バージョン」と明記するだけで保存率が上がる。",
            "trend_overlap": ["保護者対応", "学級経営", "新年度"],
        },
        {
            "id": "past_005",
            "title": "部活を断ったら起きたこと、全部話します",
            "period": "2025年4月16日",
            "media_type": "VIDEO",
            "url": "https://www.instagram.com/p/past_sample005/",
            "like_count": 2341,
            "comments_count": 287,
            "engagement": 3202,
            "caption_snippet": "【部活を断ったらこうなりました】\n\n怖くて断れない先生へ。\n実際に断った私のリアルを話します。\n\n#部活問題 #教員の働き方 #部活動地域移行",
            "hashtags": ["#部活問題", "#教員の働き方", "#部活動地域移行"],
            "what_worked": "「断ったらどうなる？」という恐怖への直接的な答えが刺さった。全年齢・全校種の先生からコメントが集まった。シェア数が過去最多。",
            "seasonal_match": False,
            "repurpose_idea": "部活地域移行のニュースと連動させて「2026年版・断り方の最新事情」として出すと伸びる。",
            "trend_overlap": ["部活問題", "教員の働き方", "部活動地域移行"],
        },
    ]
